### PR TITLE
Update agile-development.txt

### PR DESCRIPTION
**Pull request by j3ang**

### CODE REVIEW

**Comment by karlstolley** [comment]
Glad you figured out pull requests, but I won't be pulling anyone's assignments into the main repo :)

**Comment by j3ang** [comment]
oh I was trying to make sure wether I did it right to submit. 

So basically we just need to fork your repository overtime and make commits to branch?

Thanks!

**Comment by karlstolley** [comment]
That's right -- just email me a link to your repo, Junfeng.

**Comment by j3ang** [comment]
Do we need to email you the link every time?
https://github.com/jwang206/itmd362-pp https://github.com/jwang206/itmd362-pp

**Comment by karlstolley** [comment]
No -- just email once and I'll keep track of where to expect your work.

**Comment by j3ang** [comment]
Ok Thanks!

**Pull request closed without merging**
